const mongoose =require('mongoose')
const {ObjectId} =mongoose.Schema.Types
const userSchema=new mongoose.Schema({
    emp_id:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    org_name:{
        type:String,
        required:true
    },
    mobile:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    id_pic:{
        type:String,
    },
    orders:[
        {
            order:[
                {
                    title:{
                        type:String
                    },
                    details:{
                        type:String
                    },
                    type:{
                        type:String
                    },
                    img:{
                        type:String
                    },
                    price:{
                        type:String
                    },
                    qty:{
                        type:Number
                    }
                }
            ]
        }
    ]
})

mongoose.model("Users",userSchema);